# Generated by Django 5.0.14 on 2026-09-28 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0017_pathogeninteraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("classify", "Classify"), ("pair", "Compare pairs")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("items", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game_round",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GameAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("classify", "Classify"), ("pair", "Compare pairs")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        help_text="Position of the item in its round."
                    ),
                ),
                ("is_check", models.BooleanField(db_index=True, default=False)),
                ("skipped", models.BooleanField(default=False)),
                ("subfamily", models.CharField(blank=True, max_length=100)),
                ("tribe", models.CharField(blank=True, max_length=100)),
                ("genus", models.CharField(blank=True, max_length=100)),
                ("species", models.CharField(blank=True, max_length=100)),
                (
                    "pair_answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("different", "Different subfamily"),
                            ("subfamily", "Same subfamily"),
                            ("tribe", "Same tribe"),
                            ("genus", "Same genus"),
                            ("species", "Same species"),
                            ("unsure", "Not sure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("correct_subfamily", models.BooleanField(blank=True, null=True)),
                ("correct_tribe", models.BooleanField(blank=True, null=True)),
                ("correct_genus", models.BooleanField(blank=True, null=True)),
                ("correct_species", models.BooleanField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_answers",
                        to="beetles_app.beetles",
                    ),
                ),
                (
                    "roi_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_answers_as_b",
                        to="beetles_app.beetles",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="beetles_app.gameround",
                    ),
                ),
            ],
            options={
                "db_table": "game_answer",
                "indexes": [
                    models.Index(
                        fields=["player", "mode", "is_check"],
                        name="game_answer_player_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="gameanswer",
            constraint=models.UniqueConstraint(
                fields=("round", "index"), name="game_answer_round_index_uniq"
            ),
        ),
    ]
