# Generated by Django 5.0.14 on 2026-09-28 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_reference_labels(apps, schema_editor):
    """Copy the ROI's current label onto scored answers saved before these fields existed."""
    GameAnswer = apps.get_model("beetles_app", "GameAnswer")
    qs = GameAnswer.objects.filter(is_check=True, ref_genus="").select_related("roi__taxon")
    for answer in qs.iterator():
        taxon = answer.roi.taxon
        if taxon is None:
            continue
        answer.ref_subfamily = taxon.subfamily or ""
        answer.ref_tribe = taxon.tribe or ""
        answer.ref_genus = taxon.genus or ""
        answer.ref_species = taxon.species or ""
        answer.save(update_fields=["ref_subfamily", "ref_tribe", "ref_genus", "ref_species"])


class Migration(migrations.Migration):
    # Reviewed for test_deploy_safety: reads GameAnswer and its ROI's taxon, and writes only the
    # new ref_* columns of scored GameAnswer rows. Touches no other table or column.
    DATA_MIGRATION_REVIEWED = "backfill of GameAnswer.ref_* from the ROI taxon (new columns only)"


    dependencies = [
        ("beetles_app", "0018_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoiDifficulty",
            fields=[
                (
                    "roi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="difficulty",
                        serialize=False,
                        to="beetles_app.beetles",
                    ),
                ),
                ("model_difficulty", models.FloatField(blank=True, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("model_updated_at", models.DateTimeField(blank=True, null=True)),
                ("game_difficulty", models.FloatField(blank=True, null=True)),
                ("game_answers", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_roi_difficulty",
            },
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="ref_genus",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="ref_species",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="ref_subfamily",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="ref_tribe",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="response_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time from the item appearing to the answer, as reported by the browser.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LabelReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("dismissed", "Dismissed")],
                        max_length=10,
                    ),
                ),
                ("subfamily", models.CharField(blank=True, max_length=100)),
                ("tribe", models.CharField(blank=True, max_length=100)),
                ("genus", models.CharField(blank=True, max_length=100)),
                ("species", models.CharField(blank=True, max_length=100)),
                (
                    "trusted_rank",
                    models.CharField(
                        blank=True,
                        help_text="Deepest rank backed by a proven expert when reviewed.",
                        max_length=10,
                    ),
                ),
                (
                    "answers",
                    models.PositiveIntegerField(
                        default=0, help_text="Game answers on the ROI when reviewed."
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_label_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_reviews",
                        to="beetles_app.beetles",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beetles_app.taxon",
                    ),
                ),
            ],
            options={
                "db_table": "game_label_review",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=10)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("judged", models.PositiveIntegerField(default=0)),
                ("lower_bound", models.FloatField(default=0.0)),
                ("proven", models.BooleanField(db_index=True, default=False)),
                ("proven_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game_player_skill",
            },
        ),
        migrations.AddConstraint(
            model_name="playerskill",
            constraint=models.UniqueConstraint(
                fields=("player", "rank", "branch"), name="game_skill_uniq"
            ),
        ),
        migrations.RunPython(backfill_reference_labels, migrations.RunPython.noop),
    ]
