# Generated by Django 5.0.14 on 2026-09-28 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0019_game_expertise"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameanswer",
            name="score_hold",
            field=models.BooleanField(
                default=False,
                help_text="Left out of scores: the player reported this ROI and the report is open, or the ROI stopped being a valid reference.",
            ),
        ),
        migrations.CreateModel(
            name="GameReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_label", "The name looks wrong"),
                            ("bad_box", "The box doesn't fit the beetle"),
                            ("bad_image", "Photo problem (blurry, not a beetle, ...)"),
                            ("other", "Something else"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=1000)),
                ("was_validated", models.BooleanField(default=False)),
                (
                    "label_at_report",
                    models.CharField(
                        blank=True,
                        help_text="valid_species_id when reported",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("corrected", "Corrected"),
                            ("confirmed", "Label confirmed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("staff_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="beetles_app.gameanswer",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_game_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_reports",
                        to="beetles_app.beetles",
                    ),
                ),
            ],
            options={
                "db_table": "game_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="gamereport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("roi", "reporter"),
                name="game_report_one_open_per_player",
            ),
        ),
    ]
