# Generated by Django 5.0.14 on 2026-09-30 15:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0021_modelprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("affiliation", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField(blank=True)),
                (
                    "areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keys of the parts of the site they asked for.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "granted_role",
                    models.CharField(
                        blank=True,
                        help_text="member or curator, once approved.",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the approvers were emailed.",
                        null=True,
                    ),
                ),
                (
                    "notify_error",
                    models.CharField(
                        blank=True,
                        help_text="Why the approvers could not be emailed.",
                        max_length=255,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account created or updated when approved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "access_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("status", "pending")),
                name="access_request_one_pending_per_email",
            ),
        ),
    ]
