# Generated by Django 5.0.14 on 2026-09-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0024_areagrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the applicant confirmed their email address. Approvers only see confirmed requests.",
                null=True,
            ),
        ),
    ]
