# Generated by Django 5.0.14 on 2026-10-01 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("beetles_app", "0025_accessrequest_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerPoints",
            fields=[
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="points",
                        serialize=False,
                        to="beetles_app.gameanswer",
                    ),
                ),
                ("points", models.FloatField(default=0.0)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("truth", "Scored against a validated label"),
                            ("consensus", "Agreement with stronger players"),
                            ("unsure", "Not sure / skipped"),
                            ("none", "Not scored (yet)"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="How the points were made up, for the player's feedback.",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_answer_points",
            },
        ),
        migrations.CreateModel(
            name="PlayerScore",
            fields=[
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="game_score",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("score", models.FloatField(db_index=True, default=0.0)),
                ("rating", models.FloatField(default=0.0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                (
                    "judged",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Judged ranks on validated beetles (first sightings).",
                    ),
                ),
                (
                    "viewed",
                    models.PositiveIntegerField(
                        default=0, help_text="Beetles shown and answered or skipped."
                    ),
                ),
                ("labelled", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_player_score",
            },
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="is_retry",
            field=models.BooleanField(
                default=False,
                help_text="A validated beetle shown again so the player can learn it. Earns points, but is left out of accuracy and expertise, which only count the first time a beetle is seen.",
            ),
        ),
    ]
