# Generated by Django 5.0.14 on 2026-10-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("beetles_app", "0026_game_scoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePreference",
            fields=[
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="game_preference",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "focus_rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Everything"),
                            ("subfamily", "Subfamily"),
                            ("tribe", "Tribe"),
                            ("genus", "Genus"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "focus_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_preference",
            },
        ),
    ]
