# Generated by Django 5.0.14 on 2026-10-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0027_game_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameanswer",
            name="new_species",
            field=models.BooleanField(
                blank=True,
                help_text="The species the player named had no validated images when they named it. If the beetle is later validated as that species, the player is credited with a new species (SpeciesDiscovery).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="covered",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="required",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="species_done",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerskill",
            name="species_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SpeciesDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genus", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="beetles_app.gameanswer",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_discoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_discoveries",
                        to="beetles_app.beetles",
                    ),
                ),
            ],
            options={
                "db_table": "game_species_discovery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="speciesdiscovery",
            constraint=models.UniqueConstraint(
                fields=("player", "roi"), name="game_discovery_uniq"
            ),
        ),
    ]
