# Generated by Django 5.0.14 on 2026-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0028_game_coverage_discoveries"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepreference",
            name="play_mode",
            field=models.CharField(
                choices=[
                    ("both", "Both"),
                    ("classify", "Name That Beetle"),
                    ("pair", "Family Ties"),
                ],
                default="both",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gameanswer",
            name="mode",
            field=models.CharField(
                choices=[
                    ("classify", "Classify"),
                    ("pair", "Compare pairs"),
                    ("mixed", "Mixed"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gameround",
            name="mode",
            field=models.CharField(
                choices=[
                    ("classify", "Classify"),
                    ("pair", "Compare pairs"),
                    ("mixed", "Mixed"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
