# Generated by Django 5.0.14 on 2026-10-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0029_game_mixed_feed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameanswer",
            name="validated_later",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="The beetle was not validated when answered but has been since. Its correct_* and ref_* fields are then filled from the validated name, so the answer counts towards accuracy and expertise too.",
            ),
        ),
        migrations.CreateModel(
            name="RetroCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_before", models.FloatField(default=0.0)),
                ("points_after", models.FloatField(default=0.0)),
                ("validated_name", models.CharField(blank=True, max_length=200)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retro_credit",
                        to="beetles_app.gameanswer",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retro_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game_retro_credit",
                "ordering": ["-created_at"],
            },
        ),
    ]
