# Generated by Django 5.0.14 on 2026-10-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0030_game_retro_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepreference",
            name="granted_perks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Unlocks a superuser granted whatever the player\'s level (game_levels.PERKS keys, or "all"). For people who need the features, and for testing.',
            ),
        ),
    ]
